version: '3.7'

services:
  userservice:
    image: perime-user-ms:latest
    depends_on: 
      - "perime-user-db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
     
  perime-user-db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./DBscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck: 
      test: "psql -u $$POSTGRES_USER -p $$POSTGRES_PASSWORD $$POSTGRES_DB"
      interval: 20s
      timeout: 5s
      retries: 10
    environment: 
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "perime-user-db"
   
volumes: 
  db_volume: