version: '3.7'


networks: 
  userservice-dev:
    driver: bridge

services:
  userservice:
    image: perime-user-ms:latest
    depends_on: 
      - "perime-user-db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment: 
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=perime-user-db;username=postgresuser;password=admin"
    networks: 
      - userservice-dev

  perime-user-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./DBscripts/scriptPostgresCreate.sql :/docker-entrypoint-initdb.d/scriptPostgresCreate.sql
    environment: 
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "perime-user-db"
    networks: 
      - userservice-dev

volumes: 
  db_volume: