version: '3.7'

services:
  userservice:
    image: perime-user-ms:latest
    depends_on: 
      - "userdatabase"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
<<<<<<< HEAD
      - "5000:80"
     
  userdatabase:
=======
      - "5001:5001"
    environment: 
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=perime-user-db;username=postgresuser;password=admin"
    networks: 
      - userservice-dev

  perime-user-db:
>>>>>>> c7985f98c838124986e4592584f07e57ab1afdfa
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./DBscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck: 
      test: "psql -u $$POSTGRES_USER -p $$POSTGRES_PASSWORD $$POSTGRES_DB"
      interval: 20s
      timeout: 5s
      retries: 10
    environment: 
      POSTGRES_USER: "postgresuser"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "perime-user-db"
   
volumes: 
  db_volume: