version: '3.4'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
